import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseYaml as parseYAML } from "@trustforge-protocol/types";

const HEADER =
  "// GENERATED by `tf-schema codegen --target agent-contract-ts` — DO NOT EDIT BY HAND.\n\n";

function toPascalIdent(s: string): string {
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter((p) => p.length > 0)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function toScreamingSnake(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

export function generateAgentContractTs(specPath: string): string {
  const raw = readFileSync(specPath, "utf8");
  const contract = parseYAML(raw) as Record<string, unknown>;
  const project = String(contract.project ?? "unknown");
  const actions = ((contract.actions as Record<string, unknown>[]) ?? []).map((a) => ({
    name: String(a.name),
    risk: String(a.risk),
    approval: a.approval as string | undefined,
    proof: a.proof as string | undefined,
    reversible: a.reversible as boolean | undefined,
    danger_tags: (a.danger_tags as string[] | undefined) ?? [],
    allow_targets: (a.allow_targets as string[] | undefined) ?? [],
    deny_targets: (a.deny_targets as string[] | undefined) ?? [],
    description: a.description as string | undefined,
  }));

  const lines: string[] = [HEADER];
  lines.push(
    `import { AgentGuard, type GuardDecision, type GuardQuery } from "@trustforge-protocol/types";`,
    "",
    `/** Loaded contract for project "${project}". */`,
    `export const CONTRACT = ${JSON.stringify(contract, null, 2)} as const;`,
    "",
  );

  const actionUnion = actions.length > 0
    ? actions.map((a) => JSON.stringify(a.name)).join(" | ")
    : "never";
  lines.push(`export type Action = ${actionUnion};`, "");

  // Per-action metadata constants.
  for (const a of actions) {
    const constName = toScreamingSnake(a.name.replace(/\./g, "_")) + "_META";
    lines.push(
      `export const ${constName} = ${JSON.stringify(
        {
          name: a.name,
          risk: a.risk,
          approval: a.approval,
          proof: a.proof,
          reversible: a.reversible,
          danger_tags: a.danger_tags,
          allow_targets: a.allow_targets,
          deny_targets: a.deny_targets,
          description: a.description,
        },
        null,
        2,
      )} as const;`,
      "",
    );
  }

  lines.push(
    `/** Creates a pre-wired AgentGuard bound to this contract. */`,
    `export function createAgentGuard(options?: Parameters<typeof AgentGuard.fromContract>[1]): AgentGuard {`,
    `  return AgentGuard.fromContract(CONTRACT, options);`,
    `}`,
    "",
    `/** Typed wrapper around guard.check so TS catches unknown action names. */`,
    `export function checkAction(`,
    `  guard: AgentGuard,`,
    `  action: Action,`,
    `  target?: string,`,
    `  actor?: string,`,
    `): GuardDecision {`,
    `  const query: GuardQuery = { action, target, actor };`,
    `  return guard.check(query);`,
    `}`,
    "",
  );

  return lines.join("\n");
}

export function writeAgentContractTsOutput(specPath: string, outDir: string): string[] {
  mkdirSync(outDir, { recursive: true });
  const content = generateAgentContractTs(specPath);
  const baseName = `${toPascalIdent(String((parseYAML(readFileSync(specPath, "utf8")) as Record<string, unknown>).project ?? "contract"))}Contract`;
  const fileName = `${baseName.toLowerCase()}.ts`;
  writeFileSync(join(outDir, fileName), content);
  return [fileName];
}
