import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYAML } from "yaml";

const HEADER = `// GENERATED by \`tf-schema codegen --target agent-contract-rust\` — DO NOT EDIT BY HAND.

#![allow(dead_code, non_upper_case_globals, clippy::all)]

use serde_json::{json, Value};
use tf_types::guard::{AgentGuard, GuardDecision, GuardQuery};
`;

function snake(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, "_").toLowerCase();
}

function screamingSnake(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

function snakeFile(s: string): string {
  return snake(s).replace(/^_+|_+$/g, "");
}

export function generateAgentContractRust(specPath: string): string {
  const raw = readFileSync(specPath, "utf8");
  const contract = parseYAML(raw) as Record<string, unknown>;
  const actions = ((contract.actions as Record<string, unknown>[]) ?? []).map((a) => ({
    name: String(a.name),
    risk: String(a.risk),
    approval: a.approval as string | undefined,
    danger_tags: (a.danger_tags as string[] | undefined) ?? [],
  }));

  const lines: string[] = [HEADER, ""];
  lines.push(
    `/// Canonical JSON representation of the bound contract.`,
    `pub fn contract() -> Value {`,
    `    serde_json::from_str::<Value>(CONTRACT_JSON).expect("embedded contract parses")`,
    `}`,
    "",
    `const CONTRACT_JSON: &str = ${JSON.stringify(JSON.stringify(contract))};`,
    "",
    `/// Build an AgentGuard pre-wired to this contract.`,
    `pub fn create_agent_guard() -> AgentGuard {`,
    `    AgentGuard::from_contract(&contract())`,
    `}`,
    "",
    `/// Typed wrapper for guard.check; panics if the action name is not declared in this contract.`,
    `pub fn check_action(guard: &AgentGuard, action: &str, target: Option<String>, actor: Option<String>) -> GuardDecision {`,
    `    let q = GuardQuery {`,
    `        action: action.to_string(),`,
    `        target,`,
    `        actor,`,
    `    };`,
    `    guard.check(&q)`,
    `}`,
    "",
  );

  // Per-action action-name constants.
  for (const a of actions) {
    const constName = `ACTION_${screamingSnake(a.name.replace(/\./g, "_"))}`;
    lines.push(`pub const ${constName}: &str = ${JSON.stringify(a.name)};`);
  }
  lines.push("");

  return lines.join("\n");
}

export function writeAgentContractRustOutput(specPath: string, outDir: string): string[] {
  mkdirSync(outDir, { recursive: true });
  const content = generateAgentContractRust(specPath);
  const contract = parseYAML(readFileSync(specPath, "utf8")) as Record<string, unknown>;
  const fileName = `${snakeFile(String(contract.project ?? "contract"))}.rs`;
  writeFileSync(join(outDir, fileName), content);
  return [fileName];
}
