import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { Prop, TypeDecl } from "./model";
import { loadRpcSpec, type RpcMethod, type RpcServiceModel } from "./rpc-model";

const HEADER = `// GENERATED by \`tf-schema codegen --target rpc-rust\` — DO NOT EDIT BY HAND.

#![allow(unused_imports, non_camel_case_types, non_snake_case, clippy::all)]

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tokio::sync::mpsc;

use tf_types::rpc::{RpcClient, RpcContext, RpcError, RpcServer, RpcTransport};
`;

const RUST_KEYWORDS = new Set<string>([
  "as", "async", "await", "break", "const", "continue", "crate", "dyn",
  "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
  "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
  "self", "Self", "static", "struct", "super", "trait", "true", "type",
  "unsafe", "use", "where", "while", "box", "do", "final", "macro",
  "override", "priv", "typeof", "unsized", "virtual", "yield",
]);

function snake(s: string): string {
  const base = s
    .replace(/[-.]/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/__+/g, "_")
    .replace(/^_+/, "")
    .toLowerCase();
  return RUST_KEYWORDS.has(base) ? `${base}_` : base;
}

export function generateRpcRust(spec: RpcServiceModel): string {
  const lines: string[] = [HEADER, ""];
  if (spec.description) lines.push(`/// ${spec.description}`);
  const allDecls = collectDecls(spec);
  for (const d of allDecls) lines.push(emitDecl(d));

  // Client struct
  lines.push(
    "",
    `pub struct ${spec.serviceId}Client<T: RpcTransport + 'static> {`,
    `    inner: Arc<RpcClient<T>>,`,
    `}`,
    "",
    `impl<T: RpcTransport + 'static> ${spec.serviceId}Client<T> {`,
    `    pub fn new(inner: Arc<RpcClient<T>>) -> Self {`,
    `        ${spec.serviceId}Client { inner }`,
    `    }`,
  );
  for (const m of spec.methods) lines.push(emitClientMethod(m));
  lines.push("}", "");

  // Server trait
  lines.push(
    `#[async_trait::async_trait]`,
    `pub trait ${spec.serviceId}Server: Send + Sync + 'static {`,
  );
  for (const m of spec.methods) lines.push(emitServerTraitMethod(m));
  lines.push("}", "");

  // Register helper
  lines.push(
    `pub fn register_${snake(spec.serviceId)}<T: RpcTransport + 'static>(`,
    `    server: &RpcServer<T>,`,
    `    handler: Arc<dyn ${spec.serviceId}Server>,`,
    `) {`,
  );
  for (const m of spec.methods) lines.push(emitRegisterLine(spec, m));
  lines.push("}", "");
  return lines.join("\n");
}

function collectDecls(spec: RpcServiceModel): TypeDecl[] {
  const seen = new Set<string>();
  const out: TypeDecl[] = [];
  for (const m of spec.methods) {
    for (const d of m.decls) {
      if (seen.has(d.name)) continue;
      seen.add(d.name);
      out.push(d);
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

function emitDecl(d: TypeDecl): string {
  const doc = d.description ? `/// ${d.description.replace(/\r?\n/g, " ")}\n` : "";
  if (d.kind === "enum") {
    const variants = d.enumValues.map(
      (v) => `    #[serde(rename = ${JSON.stringify(v)})]\n    ${safeVariant(v)},`,
    );
    return `${doc}#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\npub enum ${d.name} {\n${variants.join("\n")}\n}\n`;
  }
  if (d.kind === "alias") {
    return `${doc}pub type ${d.name} = ${d.rustType};\n`;
  }
  if (d.kind === "struct") {
    const fields = d.props.map(emitField).join("\n");
    return `${doc}#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\npub struct ${d.name} {\n${fields}\n}\n`;
  }
  return "";
}

function emitField(p: Prop): string {
  const rustName = snake(p.name);
  const renamed = rustName !== p.name;
  const rust = p.required ? p.rustType : `Option<${p.rustType}>`;
  const attrs: string[] = [];
  if (renamed) attrs.push(`rename = ${JSON.stringify(p.name)}`);
  if (!p.required) attrs.push(`skip_serializing_if = "Option::is_none"`, `default`);
  const attr = attrs.length > 0 ? `    #[serde(${attrs.join(", ")})]\n` : "";
  const doc = p.description ? `    /// ${p.description.replace(/\r?\n/g, " ")}\n` : "";
  return `${doc}${attr}    pub ${rustName}: ${rust},`;
}

function safeVariant(s: string): string {
  const parts = s.split(/[^A-Za-z0-9]+/).filter((p) => p.length > 0);
  if (parts.length === 0) return "Unknown";
  const pascal = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return /^[0-9]/.test(pascal) ? `V${pascal}` : pascal;
}

function emitClientMethod(m: RpcMethod): string {
  const rustName = snake(m.name);
  const doc = m.description ? `    /// ${m.description}\n` : "";
  if (m.kind === "unary") {
    return `${doc}    pub async fn ${rustName}(&self, req: &${m.requestTypeName}) -> Result<${m.responseTypeName}, tf_types::rpc::RpcCallError> {\n        let value = self.inner.call_raw(${JSON.stringify(m.name)}, serde_json::to_value(req).map_err(|e| tf_types::rpc::RpcCallError { code: tf_types::rpc::RpcErrorCode::InvalidArgument, message: e.to_string() })?).await?;\n        serde_json::from_value(value).map_err(|e| tf_types::rpc::RpcCallError { code: tf_types::rpc::RpcErrorCode::Internal, message: e.to_string() })\n    }`;
  }
  return `${doc}    pub fn ${rustName}(&self, req: &${m.requestTypeName}) -> mpsc::UnboundedReceiver<Result<${m.responseTypeName}, RpcError>> {\n        let value = serde_json::to_value(req).expect("serialize request");\n        let mut raw = self.inner.server_stream_raw(${JSON.stringify(m.name)}, value);\n        let (tx, rx) = mpsc::unbounded_channel();\n        tokio::spawn(async move {\n            while let Some(item) = raw.recv().await {\n                match item {\n                    Ok(v) => {\n                        match serde_json::from_value::<${m.responseTypeName}>(v) {\n                            Ok(parsed) => { let _ = tx.send(Ok(parsed)); },\n                            Err(e) => { let _ = tx.send(Err(RpcError { code: tf_types::rpc::RpcErrorCode::Internal, message: e.to_string() })); return; },\n                        }\n                    }\n                    Err(e) => { let _ = tx.send(Err(e)); return; },\n                }\n            }\n        });\n        rx\n    }`;
}

function emitServerTraitMethod(m: RpcMethod): string {
  const rustName = snake(m.name);
  const doc = m.description ? `    /// ${m.description}\n` : "";
  if (m.kind === "unary") {
    return `${doc}    async fn ${rustName}(&self, req: ${m.requestTypeName}, ctx: RpcContext) -> Result<${m.responseTypeName}, RpcError>;`;
  }
  return `${doc}    async fn ${rustName}(&self, req: ${m.requestTypeName}, ctx: RpcContext, tx: mpsc::UnboundedSender<Result<${m.responseTypeName}, RpcError>>);`;
}

function emitRegisterLine(spec: RpcServiceModel, m: RpcMethod): string {
  const rustName = snake(m.name);
  if (m.kind === "unary") {
    return `    {\n        let handler = handler.clone();\n        server.register_unary(\n            ${JSON.stringify(m.name)},\n            ${JSON.stringify(m.capability)},\n            Arc::new(move |req_value, ctx| {\n                let handler = handler.clone();\n                Box::pin(async move {\n                    let req: ${m.requestTypeName} = serde_json::from_value(req_value)\n                        .map_err(|e| RpcError { code: tf_types::rpc::RpcErrorCode::InvalidArgument, message: e.to_string() })?;\n                    let resp = handler.${rustName}(req, ctx).await?;\n                    serde_json::to_value(resp).map_err(|e| RpcError { code: tf_types::rpc::RpcErrorCode::Internal, message: e.to_string() })\n                })\n            }),\n        );\n    }`;
  }
  return `    {\n        let handler = handler.clone();\n        server.register_stream(\n            ${JSON.stringify(m.name)},\n            ${JSON.stringify(m.capability)},\n            Arc::new(move |req_value, ctx, tx_value| {\n                let handler = handler.clone();\n                Box::pin(async move {\n                    let req: ${m.requestTypeName} = match serde_json::from_value(req_value) {\n                        Ok(r) => r,\n                        Err(e) => { let _ = tx_value.send(Err(RpcError { code: tf_types::rpc::RpcErrorCode::InvalidArgument, message: e.to_string() })); return; },\n                    };\n                    let (inner_tx, mut inner_rx) = mpsc::unbounded_channel::<Result<${m.responseTypeName}, RpcError>>();\n                    let h = handler.clone();\n                    tokio::spawn(async move { h.${rustName}(req, ctx, inner_tx).await; });\n                    while let Some(item) = inner_rx.recv().await {\n                        let mapped = item.and_then(|v| serde_json::to_value(v).map_err(|e| RpcError { code: tf_types::rpc::RpcErrorCode::Internal, message: e.to_string() }));\n                        if tx_value.send(mapped).is_err() { return; }\n                    }\n                })\n            }),\n        );\n    }`;
}

export function writeRpcRustOutput(specPath: string, outDir: string): string[] {
  const spec = loadRpcSpec(specPath);
  mkdirSync(outDir, { recursive: true });
  const fileName = `${snake(spec.serviceId)}.rs`;
  writeFileSync(join(outDir, fileName), generateRpcRust(spec));
  return [fileName];
}
