import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { Prop, TypeDecl } from "./model";
import { loadRpcSpec, type RpcMethod, type RpcServiceModel } from "./rpc-model";

const HEADER = "// GENERATED by `tf-schema codegen --target rpc-ts` — DO NOT EDIT BY HAND.\n\n";

export function generateRpcTs(spec: RpcServiceModel): string {
  const lines: string[] = [HEADER];
  lines.push(
    `import { RpcClient, RpcServer, type RpcContext } from "@trustforge-protocol/types";`,
    "",
  );

  if (spec.description) lines.push(`/** ${spec.description} */`);
  const allDecls = collectDecls(spec);
  for (const decl of allDecls) lines.push(emitDecl(decl));

  // Client class
  lines.push("", `export class ${spec.serviceId}Client {`);
  lines.push(`  constructor(private readonly client: RpcClient) {}`);
  for (const m of spec.methods) {
    lines.push("", emitClientMethod(m));
  }
  lines.push(`}`);

  // Server interface
  lines.push("", `export interface ${spec.serviceId}Server {`);
  for (const m of spec.methods) {
    lines.push(emitServerSignature(m));
  }
  lines.push(`}`);

  // Register helper
  lines.push("", `export function register${spec.serviceId}(server: RpcServer, impl: ${spec.serviceId}Server): void {`);
  for (const m of spec.methods) {
    if (m.kind === "unary") {
      lines.push(
        `  server.registerUnary<${m.requestTypeName}, ${m.responseTypeName}>(${JSON.stringify(m.name)}, ${JSON.stringify(m.capability)}, impl.${m.name}.bind(impl));`,
      );
    } else {
      lines.push(
        `  server.registerServerStream<${m.requestTypeName}, ${m.responseTypeName}>(${JSON.stringify(m.name)}, ${JSON.stringify(m.capability)}, impl.${m.name}.bind(impl));`,
      );
    }
  }
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

function collectDecls(spec: RpcServiceModel): TypeDecl[] {
  const seen = new Set<string>();
  const out: TypeDecl[] = [];
  for (const m of spec.methods) {
    for (const d of m.decls) {
      if (seen.has(d.name)) continue;
      seen.add(d.name);
      out.push(d);
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

function emitDecl(d: TypeDecl): string {
  const doc = d.description ? `/** ${d.description.replace(/\*\//g, "*\\/")} */\n` : "";
  if (d.kind === "enum") {
    return `${doc}export type ${d.name} =\n  | ${d.enumValues.map((v) => JSON.stringify(v)).join("\n  | ")};`;
  }
  if (d.kind === "alias") {
    return `${doc}export type ${d.name} = ${d.tsType};`;
  }
  if (d.kind === "union") {
    return `${doc}export type ${d.name} = ${d.tsType};`;
  }
  if (d.kind === "struct") {
    const fields = d.props.map((p: Prop) => {
      const fdoc = p.description ? `  /** ${p.description.replace(/\*\//g, "*\\/")} */\n` : "";
      return `${fdoc}  ${identOrQuoted(p.name)}${p.required ? "" : "?"}: ${p.tsType};`;
    });
    return `${doc}export interface ${d.name} {\n${fields.join("\n")}\n}`;
  }
  return "";
}

function identOrQuoted(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function emitClientMethod(m: RpcMethod): string {
  const doc = m.description ? `  /** ${m.description} */\n` : "";
  if (m.kind === "unary") {
    return `${doc}  async ${m.name}(req: ${m.requestTypeName}): Promise<${m.responseTypeName}> {\n    return this.client.call<${m.requestTypeName}, ${m.responseTypeName}>(${JSON.stringify(m.name)}, req);\n  }`;
  }
  return `${doc}  ${m.name}(req: ${m.requestTypeName}): AsyncIterable<${m.responseTypeName}> {\n    return this.client.serverStream<${m.requestTypeName}, ${m.responseTypeName}>(${JSON.stringify(m.name)}, req);\n  }`;
}

function emitServerSignature(m: RpcMethod): string {
  if (m.kind === "unary") {
    return `  ${m.name}(req: ${m.requestTypeName}, ctx: RpcContext): Promise<${m.responseTypeName}> | ${m.responseTypeName};`;
  }
  return `  ${m.name}(req: ${m.requestTypeName}, ctx: RpcContext): AsyncIterable<${m.responseTypeName}>;`;
}

export function writeRpcTsOutput(specPath: string, outDir: string): string[] {
  const spec = loadRpcSpec(specPath);
  mkdirSync(outDir, { recursive: true });
  const fileName = `${lowerKebab(spec.serviceId)}.ts`;
  const content = generateRpcTs(spec);
  writeFileSync(join(outDir, fileName), content);
  return [fileName];
}

function lowerKebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}
