import { allModels, type Prop, type SchemaModel, type TypeDecl, type Variant } from "./model";

const HEADER = `// GENERATED by \`tf-schema codegen --target rust\` — DO NOT EDIT BY HAND.

#![allow(unused_imports, non_camel_case_types, non_snake_case, clippy::all)]

use serde::{Deserialize, Serialize};
`;

const RUST_KEYWORDS: ReadonlySet<string> = new Set([
  "as", "async", "await", "break", "const", "continue", "crate", "dyn",
  "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
  "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
  "self", "Self", "static", "struct", "super", "trait", "true", "type",
  "unsafe", "use", "where", "while", "box", "do", "final", "macro",
  "override", "priv", "typeof", "unsized", "virtual", "yield",
]);

function snake(s: string): string {
  const base = s
    .replace(/[-.]/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/__+/g, "_")
    .replace(/^_+/, "")
    .toLowerCase();
  return RUST_KEYWORDS.has(base) ? `${base}_` : base;
}

function rustModuleName(schemaName: string): string {
  return snake(schemaName.replace(/^_/, ""));
}

function safeVariant(s: string): string {
  const parts = s.split(/[^A-Za-z0-9]+/).filter((p) => p.length > 0);
  if (parts.length === 0) return "Unknown";
  const pascal = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return /^[0-9]/.test(pascal) ? `V${pascal}` : pascal;
}

function docComment(description: string | undefined, indent = ""): string {
  if (!description) return "";
  const escaped = description.replace(/\r?\n/g, " ");
  return `${indent}/// ${escaped}\n`;
}

export async function generateRust(): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const models = allModels().sort((a, b) => a.schemaName.localeCompare(b.schemaName));

  for (const m of models) {
    const file = `${rustModuleName(m.schemaName)}.rs`;
    files[file] = HEADER + "use super::*;\n\n" + m.decls
      .slice()
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(emitDecl)
      .join("\n\n") + "\n";
  }

  const modLines = models.map((m) => {
    const mod = rustModuleName(m.schemaName);
    return `pub mod ${mod};\npub use ${mod}::*;`;
  });
  files["mod.rs"] = HEADER + modLines.join("\n") + "\n";
  return files;
}

function emitDecl(d: TypeDecl): string {
  const doc = docComment(d.description);
  if (d.kind === "enum") {
    const variants = d.enumValues.map((v) => {
      return `    #[serde(rename = ${JSON.stringify(v)})]\n    ${safeVariant(v)},`;
    });
    return `${doc}#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\npub enum ${d.name} {\n${variants.join("\n")}\n}`;
  }
  if (d.kind === "alias") {
    return `${doc}pub type ${d.name} = ${d.rustType};`;
  }
  if (d.kind === "union") {
    // Rust fallback: opaque JSON value.
    return `${doc}pub type ${d.name} = serde_json::Value;`;
  }
  if (d.kind === "struct") {
    const fields = d.props.map((p: Prop) => emitField(p));
    return `${doc}#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\npub struct ${d.name} {\n${fields.join("\n")}\n}`;
  }
  // tagged-union
  const variants = d.variants.map((v: Variant) => emitVariant(v));
  return `${doc}#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\n#[serde(tag = "kind")]\npub enum ${d.name} {\n${variants.join("\n")}\n}`;
}

function emitField(p: Prop): string {
  const doc = docComment(p.description, "    ");
  const rustName = snake(p.name);
  const renamed = rustName !== p.name;
  const rust = p.required ? p.rustType : `Option<${p.rustType}>`;
  const attrs: string[] = [];
  if (renamed) attrs.push(`rename = ${JSON.stringify(p.name)}`);
  if (!p.required) attrs.push(`skip_serializing_if = "Option::is_none"`, `default`);
  const attrLine = attrs.length > 0 ? `    #[serde(${attrs.join(", ")})]\n` : "";
  return `${doc}${attrLine}    pub ${rustName}: ${rust},`;
}

function emitVariant(v: Variant): string {
  const doc = docComment(v.description, "    ");
  const fields = v.props.map((p: Prop) => {
    const rustName = snake(p.name);
    const rust = p.required ? p.rustType : `Option<${p.rustType}>`;
    const renamed = rustName !== p.name;
    const attrs: string[] = [];
    if (renamed) attrs.push(`rename = ${JSON.stringify(p.name)}`);
    if (!p.required) attrs.push(`skip_serializing_if = "Option::is_none"`, `default`);
    const attrLine = attrs.length > 0 ? `        #[serde(${attrs.join(", ")})]\n` : "";
    return `${attrLine}        ${rustName}: ${rust},`;
  });
  return `${doc}    #[serde(rename = ${JSON.stringify(v.tag)})]\n    ${safeVariant(v.name)} {\n${fields.join("\n")}\n    },`;
}

export async function writeRustOutput(outDir: string): Promise<string[]> {
  const { writeFileSync, mkdirSync } = await import("node:fs");
  mkdirSync(outDir, { recursive: true });
  const files = await generateRust();
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(`${outDir}/${name}`, content);
  }
  return Object.keys(files);
}
