import { allModels, buildSymbolRegistry, type Prop, type SchemaModel, type TypeDecl } from "./model";

const HEADER = "// GENERATED by `tf-schema codegen --target ts` — DO NOT EDIT BY HAND.\n\n";

const TYPE_IDENT_RE = /\b([A-Z][A-Za-z0-9]*)\b/g;

function collectReferencedTypes(body: string): Set<string> {
  const hits = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = TYPE_IDENT_RE.exec(body))) hits.add(m[1]!);
  return hits;
}

export async function generateTs(): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const models = allModels().sort((a, b) => a.schemaName.localeCompare(b.schemaName));
  const registry = buildSymbolRegistry(models);

  for (const m of models) {
    files[`${m.schemaName}.ts`] = emitFile(m, registry);
  }

  const barrel = models
    .filter((m) => m.decls.length > 0)
    .map((m) => `export * from "./${m.schemaName}.js";`)
    .join("\n");
  files["index.ts"] = HEADER + barrel + "\n";
  return files;
}

function emitFile(m: SchemaModel, registry: Map<string, string>): string {
  const body = m.decls
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(emitDecl)
    .join("\n\n");

  const localNames = new Set(m.decls.map((d) => d.name));
  const referenced = collectReferencedTypes(body);
  const imports = new Map<string, Set<string>>();
  for (const name of referenced) {
    const owner = registry.get(name);
    if (!owner || owner === m.schemaName) continue;
    if (localNames.has(name)) continue;
    if (!imports.has(owner)) imports.set(owner, new Set());
    imports.get(owner)!.add(name);
  }

  const importLines = [...imports.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, names]) => `import type { ${[...names].sort().join(", ")} } from "./${file}.js";`)
    .join("\n");

  const prelude = importLines ? importLines + "\n\n" : "";
  return HEADER + prelude + body + (body ? "\n" : "");
}

function docComment(description?: string): string {
  if (!description) return "";
  return `/** ${description.replace(/\*\//g, "*\\/")} */\n`;
}

function emitDecl(d: TypeDecl): string {
  const doc = docComment(d.description);
  if (d.kind === "enum") {
    return `${doc}export type ${d.name} =\n  | ${d.enumValues.map((v) => JSON.stringify(v)).join("\n  | ")};`;
  }
  if (d.kind === "alias") {
    return `${doc}export type ${d.name} = ${d.tsType};`;
  }
  if (d.kind === "union") {
    return `${doc}export type ${d.name} = ${d.tsType};`;
  }
  if (d.kind === "struct") {
    const fields = d.props.map((p: Prop) => {
      const fieldDoc = p.description ? `  /** ${p.description.replace(/\*\//g, "*\\/")} */\n` : "";
      return `${fieldDoc}  ${propertyKey(p.name)}${p.required ? "" : "?"}: ${p.tsType};`;
    });
    return `${doc}export interface ${d.name} {\n${fields.join("\n")}\n}`;
  }
  // tagged-union
  const variants = d.variants.map((v) => {
    const fields = v.props.map((p: Prop) => {
      const fieldDoc = p.description ? `    /** ${p.description.replace(/\*\//g, "*\\/")} */\n` : "";
      return `${fieldDoc}    ${propertyKey(p.name)}${p.required ? "" : "?"}: ${p.tsType};`;
    });
    const variantDoc = v.description ? `  /** ${v.description.replace(/\*\//g, "*\\/")} */\n  ` : "  ";
    return `${variantDoc}| {\n    kind: ${JSON.stringify(v.tag)};\n${fields.join("\n")}\n  }`;
  });
  return `${doc}export type ${d.name} =\n${variants.join("\n")};`;
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

export async function writeTsOutput(outDir: string): Promise<string[]> {
  const { writeFileSync, mkdirSync } = await import("node:fs");
  mkdirSync(outDir, { recursive: true });
  const files = await generateTs();
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(`${outDir}/${name}`, content);
  }
  return Object.keys(files);
}
