apiVersion: v1
kind: Service
metadata:
  name: {{ include "tf-admission-webhook.fullname" . }}
  labels: {{- include "tf-admission-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: webhook
  selector: {{- include "tf-admission-webhook.selectorLabels" . | nindent 4 }}
