// SPDX-License-Identifier: Apache-2.0 OR MIT
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// macToActorURI translates a UniFi MAC address into a TrustForge
// actor URI. The MAC is normalised to lower-hex-with-colons; we don't
// add the OUI vendor for two reasons: (1) the daemon's identity bridge
// resolves OUI from the MAC anyway, and (2) the URI must remain stable
// even when a vendor renames their OUI registration.
func macToActorURI(mac string) string {
	m := strings.ToLower(strings.TrimSpace(mac))
	if m == "" {
		return "tf:actor:host:unifi/unknown"
	}
	return "tf:actor:host:unifi/" + m
}

// macToFilename returns a filesystem-safe filename for a MAC manifest.
func macToFilename(mac string) string {
	return strings.ReplaceAll(strings.ToLower(mac), ":", "-") + ".yaml"
}

// renderClientManifest produces a deterministic, human-reviewable
// YAML body for a single client. We hand-write YAML rather than
// importing a library to keep the binary dependency-free and the
// output diff-friendly.
func renderClientManifest(c Client, decision DecideResponse) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Auto-generated by tf-unifi-sync. Do not edit by hand.\n")
	fmt.Fprintf(&b, "version: 1\n")
	fmt.Fprintf(&b, "kind: actor.host\n")
	fmt.Fprintf(&b, "actor: %s\n", macToActorURI(c.Mac))
	fmt.Fprintf(&b, "source: unifi-controller\n")
	fmt.Fprintf(&b, "attributes:\n")
	fmt.Fprintf(&b, "  mac: %s\n", strings.ToLower(c.Mac))
	if c.Hostname != "" {
		fmt.Fprintf(&b, "  hostname: %q\n", c.Hostname)
	}
	if c.IP != "" {
		fmt.Fprintf(&b, "  ip: %s\n", c.IP)
	}
	if c.Network != "" {
		fmt.Fprintf(&b, "  network: %q\n", c.Network)
	}
	if c.OUI != "" {
		fmt.Fprintf(&b, "  oui: %q\n", c.OUI)
	}
	fmt.Fprintf(&b, "  is_guest: %t\n", c.IsGuest)
	fmt.Fprintf(&b, "decision:\n")
	fmt.Fprintf(&b, "  current: %q\n", decision.Decision)
	if decision.Reason != "" {
		fmt.Fprintf(&b, "  reason: %q\n", decision.Reason)
	}
	return b.String()
}

// renderDeviceManifest does the same for /stat/device entries.
func renderDeviceManifest(d Device, decision DecideResponse) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Auto-generated by tf-unifi-sync. Do not edit by hand.\n")
	fmt.Fprintf(&b, "version: 1\n")
	fmt.Fprintf(&b, "kind: actor.device\n")
	fmt.Fprintf(&b, "actor: tf:actor:device:unifi/%s\n", strings.ToLower(d.Mac))
	fmt.Fprintf(&b, "source: unifi-controller\n")
	fmt.Fprintf(&b, "attributes:\n")
	fmt.Fprintf(&b, "  mac: %s\n", strings.ToLower(d.Mac))
	if d.Name != "" {
		fmt.Fprintf(&b, "  name: %q\n", d.Name)
	}
	if d.Type != "" {
		fmt.Fprintf(&b, "  type: %q\n", d.Type)
	}
	if d.Model != "" {
		fmt.Fprintf(&b, "  model: %q\n", d.Model)
	}
	fmt.Fprintf(&b, "  adopted: %t\n", d.Adopted)
	fmt.Fprintf(&b, "decision:\n")
	fmt.Fprintf(&b, "  current: %q\n", decision.Decision)
	if decision.Reason != "" {
		fmt.Fprintf(&b, "  reason: %q\n", decision.Reason)
	}
	return b.String()
}

// writeManifest writes a manifest body to disk atomically.
func writeManifest(outDir, name, body string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	tmp := filepath.Join(outDir, name+".tmp")
	final := filepath.Join(outDir, name)
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, final)
}

// reconcile is one tick of the main loop, broken out for testability.
func reconcile(ctx context.Context, u *UniFi, dec *Decider, outDir string) error {
	clients, err := u.ListClients(ctx)
	if err != nil {
		return fmt.Errorf("list clients: %w", err)
	}
	for _, c := range clients {
		dr := DecideRequest{
			Actor:  macToActorURI(c.Mac),
			Action: "unifi.client.connected",
			Target: c.Network,
		}
		resp, err := dec.Decide(ctx, dr)
		if err != nil {
			log.Printf("decide(%s) failed: %v", c.Mac, err)
			resp = &DecideResponse{Decision: "deny", Reason: err.Error()}
		}
		body := renderClientManifest(c, *resp)
		if err := writeManifest(filepath.Join(outDir, "clients"), macToFilename(c.Mac), body); err != nil {
			log.Printf("write manifest %s: %v", c.Mac, err)
			continue
		}
		log.Printf("client mac=%s decision=%s", c.Mac, resp.Decision)
	}

	devices, err := u.ListDevices(ctx)
	if err != nil {
		return fmt.Errorf("list devices: %w", err)
	}
	for _, d := range devices {
		dr := DecideRequest{
			Actor:  "tf:actor:device:unifi/" + strings.ToLower(d.Mac),
			Action: "unifi.device.adopted",
			Target: d.Type,
		}
		resp, err := dec.Decide(ctx, dr)
		if err != nil {
			log.Printf("decide(device %s) failed: %v", d.Mac, err)
			resp = &DecideResponse{Decision: "deny", Reason: err.Error()}
		}
		body := renderDeviceManifest(d, *resp)
		if err := writeManifest(filepath.Join(outDir, "devices"), macToFilename(d.Mac), body); err != nil {
			log.Printf("write manifest device %s: %v", d.Mac, err)
			continue
		}
		log.Printf("device mac=%s decision=%s", d.Mac, resp.Decision)
	}
	return nil
}
